# .github/workflows/prisma-cloud-scan.yml

name: Prisma Cloud IaC Scan

# This section defines when the workflow will run.
# Here, it runs on every push to the 'main' branch and on pull requests targeting 'main'.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prisma_cloud_scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository so the action can access your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run Prisma Cloud IaC Scan
      # This single action downloads the scanner, authenticates, and runs the scan.
      - name: Run Prisma Cloud Scan
        uses: bridgecrewio/checkov-action@v12 # Using a stable version tag
        with:
          # Authenticate with Prisma Cloud using the secrets you configured
          api-key: ${{ secrets.PRISMA_ACCESS_KEY_ID }}::${{ secrets.PRISMA_SECRET_KEY }}
          prisma-api-url: ${{ secrets.PRISMA_API_URL }}

          # Define what to scan
          directory: .
          framework: terraform,kubernetes # Scan for both Terraform and Kubernetes files. Add others as needed.
