# .github/workflows/prisma-cloud-scan.yml

name: Prisma Cloud IaC Scan

# This section defines when the workflow will run.
# The specific triggers are now defined within each job.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This job runs on pull requests and will FAIL if issues are found.
  # It performs a full scan on all the code in the pull request branch.
  scan_pull_request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prisma Cloud Scan on PR
        uses: bridgecrewio/checkov-action@v12
        with:
          api-key: ${{ secrets.PRISMA_ACCESS_KEY_ID }}::${{ secrets.PRISMA_SECRET_KEY }}
          prisma-api-url: ${{ secrets.PRISMA_API_URL }}
          directory: .
          #framework: terraform,kubernetes
          # By default, this will fail the job if issues are found in the scan.

  # This job runs only on pushes to the 'main' branch for reporting.
  # It will NOT fail, ensuring the main branch pipeline status reflects success.
  scan_main_and_report:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Prisma Cloud Scan on Main
        uses: bridgecrewio/checkov-action@v12
        with:
          api-key: ${{ secrets.PRISMA_ACCESS_KEY_ID }}::${{ secrets.PRISMA_SECRET_KEY }}
          prisma-api-url: ${{ secrets.PRISMA_API_URL }}
          directory: .
          #framework: terraform,kubernetes
          # This line ensures the pipeline passes even if issues are found on the main branch.
          soft_fail: true
